# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Jazz On the Move' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Jazz On the Move
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'SwiftyJSON'
  pod 'SwiftKeychainWrapper'
  pod 'IQKeyboardManagerSwift'
  pod 'JGProgressHUD'
  pod 'BadgeHub'
  pod 'KSImageCarousel'
  pod 'SPIndicator'
  pod 'YouTubePlayer'


end
